### ISSUE TITLE
When is the SYSU-30k  announced?

### ISSUE THREAD

**Issue by shanglidan** [wanggrun/SYSU-30k#1]
Hello,
When is the SYSU-30k  announced?

**Comment by wanggrun** [comment]
> Hello,
> When is the SYSU-30k announced?

Hi, thanks a lot for the interest in SYSU-30k. The dataset will be available after the reviewing process of our paper.

**Comment by finger-monkey** [comment]
为什么现在数据集和代码还没有开源？

**Comment by wanggrun** [comment]
@finger-monkey 非常感谢您的关注。我们的论文依然在审稿过程当中。

**Comment by finger-monkey** [comment]
好的，感谢您的回复。祝您一切顺利。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Guangrun Wang (王广润)"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 下午5:24
收件人:&nbsp;"wanggrun/SYSU-30k"<SYSU-30k@noreply.github.com&gt;;
抄送:&nbsp;"Finger Monkey"<1286670508@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wanggrun/SYSU-30k] When is the SYSU-30k  announced? (#1)




@finger-monkey 非常感谢您的关注。我们的论文依然在审稿过程当中。

**Comment by chengxianda54321** [comment]
您好，请问什么时候会开源数据集和代码呢？

**Comment by wanggrun** [comment]
@chengxianda54321 您好。非常感谢您的关注。我们的论文依然在审稿过程当中。谢谢。

**Comment by finger-monkey** [comment]
我记得你们好像是发表在cvpr上面吧,cvpr2020的论文不是已经发布出来了吗？

**Comment by chengxianda54321** [comment]
> @chengxianda54321 您好。非常感谢您的关注。我们的论文依然在审稿过程当中。谢谢。

好的，感谢您的回复。祝您顺利，期待开源

**Comment by wanggrun** [comment]
@finger-monkey 谢谢。我们没有把它投稿到CVPR 2020哦。我们是投了期刊。

**Comment by wanggrun** [comment]
谢谢。SYSU-30k已公开。

**Comment by wanggrun** [comment]
Thank you for your interest in our project! SYSU-30k has been announced.
