### ISSUE TITLE
report new result on the SYSU-30k test set

### ISSUE THREAD

**Issue by zhouyiji** [wanggrun/SYSU-30k#11]
测试了[IICS](https://github.com/SY-Xuan/IICS)中在market数据集上训的模型在SYSU-30k-test上的效果，挺厉害的。。。

    Rank@1:0.360000 Rank@5:0.440000 Rank@10:0.464000 mAP:0.380623

<img width="505" alt="iics_market_on_sysu" src="https://user-images.githubusercontent.com/10681606/133711658-f02db7c4-d3b7-4e7b-933e-9ef2cec79f7b.png">

**Comment by wanggrun** [comment]
@zhouyiji 非常感谢您！我们把这个结果放在ReadMe中。

**Comment by wanggrun** [comment]
@zhouyiji 非常感谢您。相关结果也加到["paperswithcode.com"](https://paperswithcode.com/sota/person-re-identification-on-sysu-30k)中了。谢谢。
