### ISSUE TITLE
CAVIAR dataset test results

### ISSUE THREAD

**Issue by InstantWindy** [wanggrun/SYSU-30k#14]
Hi. I tried to use the repository to test the CAVIAR dataset, but it didn't work very well. So do you have a download link for this processed dataset? Thanks.

**Comment by wanggrun** [comment]
Dear @InstantWindy , thank you so much for your interest in our work! Regarding the CAVIAR dataset, we recommend that you contact the authors of the dataset. 

Best wishes to you,
