### ISSUE TITLE
Missing 0000000000/* folder in the training set

### ISSUE THREAD

**Issue by JegernOUTT** [wanggrun/SYSU-30k#15]
Hello, thank you for your work!
I found out that the folder **0000000000/*** is missing. Probably, it should be in the **sysu_train_set_all_part1.tar**, but there is no such folder. 
Can you give me some clue about the missing folder?

**Comment by wanggrun** [comment]
Dear @JegernOUTT , Thank you so much for your interest in our work! There is no folder named "0000000000/" in this dataset. Please refer to train.txt for the detail.

Best regards,
