### ISSUE TITLE
解压后一个文件夹就是一个ID吗

### ISSUE THREAD

**Issue by guanyonglai** [wanggrun/SYSU-30k#3]
下了几个压缩包解压了准备看下结果，请问解压后一个文件夹里的图片就是一个ID吗，还是需要代码处理才能得到ID的分类。

**Comment by wanggrun** [comment]
非常感谢您的下载。解压后一个文件夹里的图片就是一个图片。

**Comment by hzphzp** [comment]
> 非常感谢您的下载。解压后一个文件夹里的图片就是一个图片。

可是看上去，不像是一个文件夹下面是同一个人诶？请问如何获得图片的ground truth ID呢？

**Comment by wanggrun** [comment]
@hzphzp 非常感谢您对我们的工作的关注。SYSU-30k数据集的训练集，重点关注弱监督学习和自监督学习。因此，训练集中并没有每一张图的准确标注。但依然可能学习。尤其是，最近我们注意到，SYSU-30k数据集在self-supervised learning中具有十分promising的效果，甚至超过了有监督学习的迁移学习效果。

最好的祝愿，
