### ISSUE TITLE
Possible alternate ways of downloading the dataset?

### ISSUE THREAD

**Issue by superaha** [wanggrun/SYSU-30k#5]
Hello, thanks for sharing this resource to the research community.

However, it seems to me that BaiduPan is not available outside China.

Do you have other backup locations for storing this dataset? For example, Google Drive or Microsoft OneDrive, or Dropbox?

Thanks again.

**Comment by wanggrun** [comment]
Thank you for your interest in our dataset. Due to the memory cost, we cannot upload the dataset to other locations at present. However, we will upload it later.

**Comment by wanggrun** [comment]
Dear @superaha , thank you so much for your interest in our work. The SYSU-30k dataset is also uploaded to Google driver. Both Google driver and Baidu pan are available now.

Best regards,
