### ISSUE TITLE
About Test

### ISSUE THREAD

**Issue by babyta** [wanggrun/SYSU-30k#6]
你好跑测试的时候出现了这个信息，请问在代码里要怎么修改？
Traceback (most recent call last):
  File "test_sysu_combine.py", line 212, in <module>
    gallery_feature = extract_feature(model,dataloaders['gallery'])
  File "test_sysu_combine.py", line 154, in extract_feature
    features = torch.cat((features,ff), 0)
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 20756439040 bytes. Buy new RAM!

**Comment by wanggrun** [comment]
谢谢您的关注和使用！

出现这个问题的原因在于，我们的测试集的查询库太大了，您的服务器memory太小了。建议您在别的电脑跑一下。或者需要以时间换空间，把查询库分成几部分，然后分别在各部分内查询挑出局部top-k,再把局部top-k合并起来，得到全局top-k。我们后续会在代码里加入这个实现。谢谢！

这也说明了我们的测试集与现实场景接近。现实中，查询库往往非常大。

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
