### ISSUE TITLE
SYSU30k-traininig

### ISSUE THREAD

**Issue by zhuyingSeu** [wanggrun/SYSU-30k#7]
Thanks for your sharing. 
How to use the SYSU30k to train the model ? By bag_level_label.json?

**Comment by wanggrun** [comment]
Thank you very much for your interest in our dataset.

For training, you might have to write a new data layer, which is very simple. You can use bag_level_label.json to write the data layer, which is organized as follows.

Let's take a part of bag_level_label.json as an example for illustration:
[
...
{"BagLabel": [3], "BagID": "bag0000000009", "BagImages": ["0000000003/*"]},
{"BagLabel": [2, 3, 4], "BagID": "bag0000000010", "BagImages": ["0000000002/*", "0000000003/*", "0000000004/*"]},
{"BagLabel": [1, 2, 3, 4, 5], "BagID": "bag0000000011", "BagImages": ["0000000001/*", "0000000002/*", "0000000003/*", "0000000004/*", "0000000005/*"]},
...
]

This indicates that all the images in ["0000000003/*"] can be assigned to a bag label [3]; and all the images in ["0000000002/*", "0000000003/*", "0000000004/*"] can be assigned to a bag label [2, 3, 4]; and all the images in ["0000000001/*", "0000000002/*", "0000000003/*", "0000000004/*", "0000000005/*"] can be assigned to a bag label [1, 2, 3, 4, 5].

As shown, the rule of the organization is straightforward to follow. Therefore, using this rule, you can also write a data layer without bag_level_label.json.

We will provide an example in the directory of DistributedTrainSYSU30k in the future.

**Comment by wanggrun** [comment]
Dear @zhuyingSeu , thank you so much for your interest in our work. A promising way to use the SYSU-30k dataset is self-supervised person re-identification. The code has been available.

Best wishes to you,
