### ISSUE TITLE
请问为什么只有当bagid=1 or 2时能够复现出结果？

### ISSUE THREAD

**Issue by Sixty-seven** [wanggrun/SYSU-30k#8]
感谢您提供开源资源，我对您的工作感兴趣，我在复现时按照demo操作，在market上请问为什么只要当bagid=1,2时能够复现出结果，而改为4或者其它参数(即一个bag中放更多id)就不能够跑出结果了？ 是不是只修改bagid这个参数不够？ 谢谢。

**Comment by wanggrun** [comment]
答：非常感谢您的关注和兴趣。当一个bag里面的ID增多时，相应的参数需要稍微调整一下。例如pair-wise term的权重。谢谢！
